### ISSUE TITLE
Pipeline for ADF 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1676]
`Dev`
- Updated after each commit on the **development** branch 
- Automated tests to run after above is completed
- Will be used for manual tests and bu reporting

`Staging`
- Using private NPM
- Deployed to if automated tests on `Dev` pass
- Automated tests to run after above after above is completed

`Master`
- Using latest main NPM
- Automated tests to run after above after above is completed

**Tasks to be completed**

- [ ] All of the above environments created
- [ ] Automation tests set to run when required 
- [ ] Monitors setup in office for environments and automation test results
- [ ] Email/slack/skype notifications if any of the above environments are down or automation tests fail
