### ISSUE TITLE
Preparation for making repositories public

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#218]
On June 30th we will make the repositories public. To be sure we have a good story there are a few things we need to make sure of

* [x] Acceptance criteria is clearly stated in GitHub Wiki
* [x] Catalog website available on a public URL
* [x] Docker instructions replaced with instructions to download Community edition with CORS module
* [x] Blog post to announce the framework
* [x] Plan Tech Talk Live to discuss the framework
* [x] Figure out naming of the repository (dev-platform-webcomponents)
* [x] Publish all the components on the public npm
