### ISSUE TITLE
Alfresco Javascript API for REST API's

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#24]
A generic, general purpose Javascript SDK that wraps around the v1 Alfresco REST API's. This could potentially be done automatically via Swagger and related tools.

**Acceptance criteria**

* [x] The SDK provides an interface that is easy to use
* [x] The SDK can be used in other contexts such as node.js and vanilla browsers/javascript
* [x] The SDK is autogenerated and/or requires minimal effort post generation to maintain
* [x] The SDK can be used to make calls to custom web scripts in the repository

_If the SDK can not be autogenerated from the OpenAPI definition we should discuss alternatives._

/* Note */
A strong requirement is that all components and services must use the v1 REST APIs. In essence this means that if you're calling a URL that doesn't start with: alfresco/api/-default-/public/... we are not to use it.

A list of the v1 REST APIs for 5.1 can be found here: https://api-explorer.alfresco.com/api-explorer

**Comment by ohej** [comment]
All the original requirements have been implemented. Closing the epic
