### ISSUE TITLE
BPM API Integration

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#336]
We need to create the equivalent of the current ECM Javascript API library also for BPM

A developer will have the choice of connecting an using two services ECM and BPM
Its Ok for now to assume SSO via matching passwords and user names but each service could also have its own login. 

You may want to create your Activiti own build with the pull request https://github.com/Alfresco/activiti-bpm-suite/pull/2061to see if that helps creating a first stub of APIs. The APIS are documented here  https://docs.alfresco.com/activiti/docs/dev-guide/1.4.0/#_rest_api

Many cover the design experience. To start with we want to be able to 
- [x] Get All Filters
- [x] Get All Tasks for a filter or All
- [x] Get the info for a task 
- [x] Get a list of Processes and the process details
- [x] Get A list Forms and the forms details
- [x] start a new process with submitting the data 
- [x] Progress a Task to the next step by submitting Data
- [x] Creating a checklist
- [x] Attaching a checklist to a task
- [x] Creating comments for a task
- [x] Listing and viewing the comments for a task
