### ISSUE TITLE
Upload component

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#42]
Uploader is initiated by file upload via button or drag and drop event

_Acceptance criteria_
- [x] "Sticky" dialog that can be minimised
- [x]  Must not block the UI whilst on screen
- [x]  Lists all uploads from the current session
- [x]  Shows overall progress - visual progress indication + number of files complete
- [x] Shows individual upload progress of each file
- [ ]  Shows folder upload progress (number of files completed out of total)
- [ ]  Cancel individual file/folder upload
- [ ]  Cancel all remaining uploads
- [x]  Drag'n'drop into document list component
