### ISSUE TITLE
Document List component

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#47]
A configurable component that renders a list of documents and folders.

_Acceptance criteria_
- [x] Ability to add/remove action buttons and drop downs
- [x] Configurable actions (what happens when you click a document?)
- [x]  Configurable columns (document title/name, thumbnail, creation date, modified date, creator, size)
- [x] Support anchor/URL based navigation
- [x]  Serve as a drop zone for drag'n'drop upload
- [x]  Ability to sort the list 

_Requirements that may be separate components_
- [x] Support pagination (might be a separate component?)
- [x] Breadcrumb (clickable navigation path showing path from top to current location)
- [ ]  Ability to create a custom rendition of the list (simple list, table view, gallery view, filmstrip view)
