### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#52]
File previewer overlays the application and presents a rendition of the file handling the
 following types of files:
- [ ]  DocumentPreview; thumbnail navigation, next/prev page, page numbering/selection, zoom in/out
- [ ]  ImagePreview; zoom in/out
- [ ]  VideoPreview; video player controls
- [ ]  AudioPreview; audia player controls

It may be worth looking into the previewer in Share.

**Acceptance criteria**
- [ ]  Configurable buttons (enable/disable/remove/add new buttons)
- [ ]  Can be used on a dedicated page or in a modal/popup
