### ISSUE TITLE
Object Picker

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#53]
A dialog that provides a way to select a document, site, folder, user or group.
In essence the object picker needs to be configurable in terms of what it needs to do, one example is what types of content can be selected (document, site, folder, user, group etc).

The default behaviour will be that a dialog appears with a search box and a document-list. On the bottom of the dialog two configurable buttons appears (`OK`/`Cancel`, `Copy`/`Cancel`, `Move`/`Cancel`, essentially it's `OK`/`Cancel` buttons, but the label needs to be configurable). 

In the document list there will be configurable tabs, one example could be `Personal files` and `Document Libraries`. Another example could be `User` and `Groups`.
The tabs serve as a way to change the starting point of the document-list.

Browsing the document-list you can select an item and click OK and an event is fired off.

From the search box in the object picker, a search is performed and tabs will be re-arranged to the context, i.e `Folders`, `Files`, `Sites`. If the object picker is being used in user/group context the tabs will change to `Users` and `Groups`

Mock-ups on what this could look like can be found here: https://issues.alfresco.com/jira/browse/SFS-474
The design will change later on, so use it mostly for structural setup.

**Acceptance criteria**
- [ ]  Use the Object Picker to implement copy and move actions for the document-list
- [ ]  Can be configured to have different "starting points" (root folders)
- [ ]  Can be configured to only allow selecting certain types of content (including custom types)
- [ ]  Can be used for both content and user/group selections
- [ ]  Configurable tabs for `Personal files`, `Document Libraries` 
- [ ]  Can be used to select multiple items
- [ ]  Can be used in form context (pre-loaded with values)
