### ISSUE TITLE
Analytics  component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#728]
We want to port all the functionality of the analytics in Activiti in the app dev framework. As minimum requirement, we want to port all the standard reports:
- [x] Process definition heat map
- [x] Process definition overview
- [x] Process instances overview
- [x] Task overview
- [x] Task service level agreement

As library, we could use the same library of the generated app: http://valor-software.com/ng2-charts/

Each report needs to have the option to be deleted and recreated.

**Comment by jsotiro** [comment]
This is a great story. Activiti has its analytics components built using a Java interface. In 1.5 we have introduced the concept of custom report interface see https://docs.alfresco.com/activiti/docs/dev-guide/1.5.0/#_implementing_custom_reports using spring beans. Like our forms  component - the new component must be capaable to render any of these beans
